{
 "title": "AWS IoT FleetWise RDB2 - Signal overview-sunjimmy@",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "vehicleName",
    "label": "Vehicle Name",
    "query": "SELECT distinct(vehicleName) FROM \"IoTFleetWiseDB-1669190634\".\"VehicleDataTable\" "
   },
   {
    "name": "aggregationInterval",
    "label": "Aggregation interval",
    "query": "100ms, 1s, 5s, 10s, 20s, 30s, 1m, 3m, 5m, 30m, 60m"
   }
  ]
 },
 "panels": [
  {
   "title": "Vehicle Speed history",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "database": "\"IoTFleetWiseDB-1669190634\"",
     "measure": "HSCANv2.VehicleSpeed",
     "rawQuery": "SELECT vehicleName, BIN(time, ${aggregationInterval}), avg(measure_value::double) AS  \"$__measure avg(${aggregationInterval})\"\nFROM $__database.$__table \nWHERE measure_name = '$__measure'  and vehicleName = '${vehicleName}'\nGROUP BY vehicleName,BIN(time, ${aggregationInterval}) \nORDER BY BIN(time, ${aggregationInterval})",
     "table": "\"VehicleDataTable\""
    }
   ]
  },
  {
   "title": "Current Vehicle Speed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "database": "\"IoTFleetWiseDB-1669190634\"",
     "measure": "HSCANv2.VehicleSpeed",
     "rawQuery": "SELECT avg(measure_value::double) AS  \"$__measure avg(${aggregationInterval})\"\nFROM $__database.$__table \nWHERE measure_name = '$__measure'  and vehicleName = '${vehicleName}' and $__timeFilter\nGROUP BY vehicleName,BIN(time, 0.1s) \nORDER BY BIN(time, 0.1s)",
     "table": "\"VehicleDataTable\""
    }
   ]
  },
  {
   "title": "Vehicle Speed Statistics",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "database": "\"IoTFleetWiseDB-1669190634\"",
     "measure": "HSCANv2.VehicleSpeed",
     "rawQuery": "SELECT avg(measure_value::double) AS  \"Average\", max(measure_value::double) AS  \"Maximum\", min(measure_value::double) AS  \"Minimum\" \nFROM $__database.$__table \nWHERE measure_name = '$__measure'  and vehicleName = '${vehicleName}' and $__timeFilter\n",
     "table": "\"VehicleDataTable\""
    }
   ]
  },
  {
   "title": "Gear Position Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 6 },
   "targets": [
    {
     "database": "\"IoTFleetWiseDB-1669190634\"",
     "measure": "HSCANv2.Gear",
     "rawQuery": "SELECT vehicleName, BIN(time, ${aggregationInterval}), avg(measure_value::bigint) AS  \"$__measure avg(${aggregationInterval})\"\nFROM $__database.$__table \nWHERE measure_name = '$__measure'  and vehicleName = '${vehicleName}'\nGROUP BY vehicleName,BIN(time, ${aggregationInterval}) \nORDER BY BIN(time, ${aggregationInterval})",
     "table": "\"VehicleDataTable\""
    }
   ]
  },
  {
   "title": "Current Gear",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "database": "\"IoTFleetWiseDB-1669190634\"",
     "measure": "HSCANv2.Gear",
     "rawQuery": "SELECT avg(measure_value::bigint) AS  \"Gear\"\nFROM $__database.$__table \nWHERE measure_name = '$__measure'  and vehicleName = '${vehicleName}' and $__timeFilter\nGROUP BY vehicleName,BIN(time, 0.1s) \nORDER BY BIN(time, 0.1s)",
     "table": "\"VehicleDataTable\""
    }
   ]
  },
  {
   "title": "Gear Position Statics",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"IoTFleetWiseDB-1669190634\"",
     "measure": "HSCANv2.Gear",
     "rawQuery": "SELECT  max(measure_value::BIGINT) AS  \"Maximum\", min(measure_value::BIGINT) AS  \"Minimum\" \nFROM $__database.$__table\nWHERE measure_name = '$__measure'  and vehicleName = '${vehicleName}' and $__timeFilter\n",
     "table": "\"VehicleDataTable\""
    }
   ]
  },
  {
   "title": "Collision Intensity Histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "forceN" } },
   "targets": [
    {
     "database": "\"IoTFleetWiseDB-1669190634\"",
     "measure": "HSCANv2.CollisionIntensity",
     "rawQuery": "SELECT vehicleName, BIN(time, ${aggregationInterval}), avg(measure_value::double) AS  \"$__measure avg(${aggregationInterval})\"\nFROM $__database.$__table \nWHERE measure_name = '$__measure'  and vehicleName = '${vehicleName}'\nGROUP BY vehicleName,BIN(time, ${aggregationInterval}) \nORDER BY BIN(time, ${aggregationInterval})",
     "table": "\"VehicleDataTable\""
    }
   ]
  },
  {
   "title": "Collision Sensor(CollisionIntensity)",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 12 },
   "targets": [
    {
     "database": "\"IoTFleetWiseDB-1669190634\"",
     "measure": "HSCANv2.CollisionIntensity",
     "rawQuery": "SELECT vehicleName AS \"Vehicle Name\", BIN(time, ${aggregationInterval}) AS \"Time of Collision\", avg(measure_value::double) AS  \"Intensity Value(N)\"\nFROM $__database.$__table \nWHERE measure_name = '$__measure'  and vehicleName = '${vehicleName}'\nGROUP BY vehicleName,BIN(time, ${aggregationInterval}) \nORDER BY BIN(time, ${aggregationInterval})",
     "table": "\"VehicleDataTable\""
    }
   ]
  },
  {
   "title": "Front Left Door Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "database": "\"IoTFleetWiseDB-1669190634\"",
     "measure": "HSCANv2.DOOR_OPEN_FL",
     "rawQuery": "SELECT vehicleName, BIN(time, ${aggregationInterval}), avg(measure_value::bigint) AS  \"$__measure avg(${aggregationInterval})\"\nFROM $__database.$__table \nWHERE measure_name = '$__measure'  and vehicleName = '${vehicleName}'\nGROUP BY vehicleName,BIN(time, 1s) \nORDER BY BIN(time, 1s)",
     "table": "\"VehicleDataTable\""
    }
   ]
  },
  {
   "title": "Front Right Door Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "database": "\"IoTFleetWiseDB-1669190634\"",
     "measure": "HSCANv2.DOOR_OPEN_FR",
     "rawQuery": "SELECT vehicleName, BIN(time, ${aggregationInterval}), avg(measure_value::bigint) AS  \"$__measure avg(${aggregationInterval})\"\nFROM $__database.$__table \nWHERE measure_name = '$__measure'  and vehicleName = '${vehicleName}'\nGROUP BY vehicleName,BIN(time, 1s) \nORDER BY BIN(time, 1s)",
     "table": "\"VehicleDataTable\""
    }
   ]
  },
  {
   "title": "Flinker",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "database": "\"IoTFleetWiseDB-1669190634\"",
     "measure": "HSCANv2.HIGH_BEAM_FLASH",
     "rawQuery": "SELECT vehicleName, BIN(time, ${aggregationInterval}), avg(measure_value::bigint) AS  \"$__measure avg(${aggregationInterval})\"\nFROM $__database.$__table \nWHERE measure_name = '$__measure'  and vehicleName = '${vehicleName}'\nGROUP BY vehicleName,BIN(time, 1s) \nORDER BY BIN(time, 1s)",
     "table": "\"VehicleDataTable\""
    }
   ]
  },
  {
   "title": "Rear Left Door Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "database": "\"IoTFleetWiseDB-1669190634\"",
     "measure": "HSCANv2.DOOR_OPEN_RL",
     "rawQuery": "SELECT vehicleName, BIN(time, ${aggregationInterval}), avg(measure_value::bigint) AS  \"$__measure avg(${aggregationInterval})\"\nFROM $__database.$__table \nWHERE measure_name = '$__measure'  and vehicleName = '${vehicleName}'\nGROUP BY vehicleName,BIN(time, 1s) \nORDER BY BIN(time, 1s)",
     "table": "\"VehicleDataTable\""
    }
   ]
  },
  {
   "title": "Rear Rear Door Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "database": "\"IoTFleetWiseDB-1669190634\"",
     "measure": "HSCANv2.DOOR_OPEN_RR",
     "rawQuery": "SELECT vehicleName, BIN(time, ${aggregationInterval}), avg(measure_value::bigint) AS  \"$__measure avg(${aggregationInterval})\"\nFROM $__database.$__table \nWHERE measure_name = '$__measure'  and vehicleName = '${vehicleName}'\nGROUP BY vehicleName,BIN(time, 1s) \nORDER BY BIN(time, 1s)",
     "table": "\"VehicleDataTable\""
    }
   ]
  },
  {
   "title": "Gas pedal position history",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "database": "\"IoTFleetWiseDB-1669190634\"",
     "measure": "HSCANv2.ThrottlePosition",
     "rawQuery": "SELECT vehicleName, BIN(time, ${aggregationInterval}), avg(measure_value::double) AS  \"$__measure avg(${aggregationInterval})\"\nFROM $__database.$__table \nWHERE measure_name = '$__measure'  and vehicleName = '${vehicleName}'\nGROUP BY vehicleName,BIN(time, ${aggregationInterval}) \nORDER BY BIN(time, ${aggregationInterval})",
     "table": "\"VehicleDataTable\""
    }
   ]
  },
  {
   "title": "Current gas pedal position",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "database": "\"IoTFleetWiseDB-1669190634\"",
     "measure": "HSCANv2.ThrottlePosition",
     "rawQuery": "SELECT avg(measure_value::double) AS  \"$__measure avg(${aggregationInterval})\"\nFROM $__database.$__table \nWHERE measure_name = '$__measure'  and vehicleName = '${vehicleName}' and $__timeFilter\nGROUP BY vehicleName,BIN(time, 0.1s) \nORDER BY BIN(time, 0.1s)",
     "table": "\"VehicleDataTable\""
    }
   ]
  },
  {
   "title": "Gas pedal statistics",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "database": "\"IoTFleetWiseDB-1669190634\"",
     "measure": "HSCANv2.ThrottlePosition",
     "rawQuery": "SELECT avg(measure_value::double) AS  \"Average\", max(measure_value::double) AS  \"Maximum\", min(measure_value::double) AS  \"Minimum\" \nFROM $__database.$__table \nWHERE measure_name = '$__measure'  and vehicleName = '${vehicleName}' and $__timeFilter\n",
     "table": "\"VehicleDataTable\""
    }
   ]
  }
 ]
}